### ISSUE TITLE
heap corruption in fir_decimate in not #if ARM_NEON path.

### ISSUE THREAD

**Issue by dennishiding** [krakenrf/heimdall_daq_fw#13]
split from [prior issue](https://github.com/krakenrf/heimdall_daq_fw/issues/12#issue-1532950671)

from decimator.log
```
double free or corruption (out)
```

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007eff478e7c73 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007eff47897986 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007eff478817f4 in __GI_abort () at abort.c:79
#4  0x00007eff478dbd5e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7eff47a1387c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007eff478f195c in malloc_printerr (str=str@entry=0x7eff47a16450 "double free or corruption (out)") at malloc.c:5659
#6  0x00007eff478f3a80 in _int_free (av=0x7eff47a51c80 <main_arena>, p=0x7eff1a374030, have_lock=<optimized out>) at malloc.c:4583
#7  0x00007eff478f6103 in __GI___libc_free (mem=<optimized out>) at malloc.c:3386
#8  0x00000000004016c0 in main ()
```
recompiling with -g:

```
#8  0x00000000004016c0 in main (argc=<optimized out>, argv=<optimized out>) at fir_decimate.c:347
```
corresponding to near end of main(): ```free(fir_input_buffer_i);```   Line number likely not exact to your repo due to additional ```log_info()``` calls added for debug while trying to diagnose.

Earlier ```#if ARM_NEON``` switches between using ```malloc()``` in the true path and ```kfr_allocate()``` in the non ARM_NEON path.

Wrapping the free()'s in similar #if ARM_NEON directives seems to resolve the issue.
```
#ifdef ARM_NEON
    free(fir_input_buffer_i);
    free(fir_input_buffer_q);
    free(fir_output_buffer_i);
    free(fir_output_buffer_q);
#else // X86
    kfr_release( fir_input_buffer_i);
    kfr_release( fir_input_buffer_q);
    kfr_release( fir_output_buffer_i);
    kfr_release( fir_output_buffer_q);
#endif
```

Seems like an easy fix,   only shows up as the application is exiting though so mostly no impact other than potential red herring when dealing with an unexpected termination.

**Comment by krakenrf** [comment]
Pretty sure this was just related to power supply issues and discussed in the other issue.
