### ISSUE TITLE
Start synthetic failed

### ISSUE THREAD

**Issue by Vol-Alex** [krakenrf/heimdall_daq_fw#16]
I use docker image https://github.com/godsic/krakensdr-containers/ . In container I run `$ ./daq_synthetic_start.sh` and get the error:
```
Traceback (most recent call last):
  File "/root/krakensdr/heimdall_daq_fw/Firmware/_testing/test_data_synthesizer.py", line 246, in <module>
    FIFO_rd_thread_inst0 = FIFO_rd_thread(M)
  File "/root/krakensdr/heimdall_daq_fw/Firmware/_testing/test_data_synthesizer.py", line 66, in __init__
    self.ctr_fifo_descriptor = open("_data_control/rec_control_fifo", 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '_data_control/rec_control_fifo'
```
Can you help to solve this problem? Thanks.

**Comment by krakenrf** [comment]
Can you give a little more information about what you are trying to achieve? The synthetic start shouldn't be used in normal use, it's mostly for development of the system.
